name = "hanyoutube"
main = "src/index.ts"
compatibility_date = "2022-12-29"
node_compat = true

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "hanyoutube_db"
database_id = "d42f565b-466d-41e5-a1b7-d568f278d74c"
preview_database_id = "d42f565b-466d-41e5-a1b7-d568f278d74c"
